name: example_app
description: Demonstrates how to use the rinf plugin.
publish_to: "none"

version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  rinf:
    path: ../
  cupertino_icons: ^1.0.2
  meta: ^1.16.0
  tuple: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
