services:
  documentation:
    build:
      context: .
      dockerfile: documentation/Dockerfile
    ports:
      - "${PORT}:80"
    restart: unless-stopped

  demo:
    build:
      context: .
      dockerfile: demo/Dockerfile
    ports:
      - "${PORT_DEMO}:80"
    restart: unless-stopped
