[package]
name = "sample_crate_second"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
# Downloaded
serde_json = { workspace = true }
# Workspace
