[package]
name = "rifs"
version = "4.1.0"
edition = "2021"
license = "MIT"
description = "Rust as your Flutter backend, Flutter as your Rust frontend"
repository = "https://github.com/cunarist/rust-in-flutter"

[dependencies]
which = "4.4.2"
