name: example_app
description: Demonstrates how to use the rinf plugin.
publish_to: "none"

version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  rinf:
    path: ../
  cupertino_icons: ^1.0.2
  protobuf: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
