name: build-test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

concurrency:
  # Cancels the workflow
  # when another event in the same context happens.
  # If it's a PR, context is the pull request number.
  # Otherwise, it uses the Git reference(branch or tag name).
  group: >
    ${{ github.workflow }}
    ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.runner }} / ${{ matrix.target }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false # Important
      matrix:
        runner: [ubuntu-latest, windows-latest, macos-latest]
        target: [android, web] # On all platforms
        include:
          # Specify targets for each platform
          - runner: ubuntu-latest
            target: linux
          - runner: windows-latest
            target: windows
          - runner: macos-latest
            target: macos
          - runner: macos-latest
            target: ios

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Protobuf compiler
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Ninja and GTK3 toolchain (Only Linux target)
        if: matrix.target == 'linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Setup Java toolchain (Only Android target)
        if: matrix.target == 'android'
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Install the CLI tool
        working-directory: rust_crate/
        run: cargo install --path ./

      - name: Create a Flutter app for testing
        working-directory: flutter_ffi_plugin/
        run: flutter create test_app

      - name: Add this framework as a dependency
        working-directory: flutter_ffi_plugin/test_app/
        run: dart pub add "rinf:{'path':'../'}"

      - name: Apply Rust template
        working-directory: flutter_ffi_plugin/test_app/
        run: rinf template

      - name: Remove the template workspace Cargo file
        uses: JesseTG/rm@v1.0.3
        with:
          path: /flutter_ffi_plugin/test_app/Cargo.toml

      - name: Add test app's crates to Cargo workspace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "example/native/*"
          replace: "test_app/native/*"
          include: Cargo.toml

      - name: Generate message files
        working-directory: flutter_ffi_plugin/test_app/
        run: rinf message

      - name: Build the example app
        if: matrix.target == 'linux'
        working-directory: flutter_ffi_plugin/test_app/
        run: flutter build linux

      - name: Build the example app
        if: matrix.target == 'android'
        working-directory: flutter_ffi_plugin/test_app/
        run: |
          flutter build apk
          flutter build appbundle

      - name: Build the example app
        if: matrix.target == 'windows'
        working-directory: flutter_ffi_plugin/test_app/
        run: flutter build windows

      - name: Build the example app
        if: matrix.target == 'macos'
        working-directory: flutter_ffi_plugin/test_app/
        run: flutter build macos

      - name: Build the example app
        if: matrix.target == 'ios'
        working-directory: flutter_ffi_plugin/test_app/
        run: flutter build ios --no-codesign

      - name: Build the example app
        if: matrix.target == 'web'
        working-directory: flutter_ffi_plugin/test_app/
        run: |
          rinf wasm --release
          flutter build web
