name: formatting-test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  # Cancels the workflow
  # when another event in the same context happens.
  # If it's a PR, context is the pull request number.
  # Otherwise, it uses the Git reference(branch or tag name).
  group: >
    ${{ github.workflow }}
    ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  dart:
    name: dart-code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Format Dart code
        run: dart format .

      - name: Verify changed files
        id: verify-changed-files
        uses: tj-actions/verify-changed-files@v16
        with:
          files: >
            **/*

      - name: Raise error if any of the files has changed
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          echo "Changed files: ${{ steps.verify-changed-files.outputs.changed_files }}"
          exit 1

  rust:
    name: rust-code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Protobuf compiler
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Clippy
        run: rustup component add clippy

      - name: Format Rust code
        run: cargo clippy --fix

      - name: Verify changed files
        id: verify-changed-files
        uses: tj-actions/verify-changed-files@v16
        with:
          files: >
            **/*

      - name: Raise error if any of the files has changed
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          echo "Changed files: ${{ steps.verify-changed-files.outputs.changed_files }}"
          exit 1

  config:
    name: other-files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check files with Prettier
        uses: creyD/prettier_action@v4.3
        with:
          dry: True
          prettier_options: >
            --write
            ./**/*.{md,yaml}
