# Build and push web apps to container registry
name: Registry Push

on:
  workflow_dispatch:

jobs:
  build-and-push-demo:
    name: Build and Push Demo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push demo image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./demo/Dockerfile
          tags: registry.cunarist.org/rinf-demo:${{ github.sha }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-and-push-docs:
    name: Build and Push Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push documentation image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./documentation/Dockerfile
          tags: registry.cunarist.org/rinf-docs:${{ github.sha }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
